### PR TITLE
Manual OKAPI Project update - ver. 1567 (rev. fbee5bf)

### PR DESCRIPTION
**Pull request by following5**
This is an OKAPI refactoring which breaks the automatic update (see https://github.com/opencaching/okapi/pull/489). @wrygiel currently has no time for OKAPI and has given me a "go" to proceed with this deployment (https://github.com/opencaching/okapi/pull/499).

This change has already been in production test at www.opencaching.de for two weeks. I have also done a code review and tests on my OCPL develsite. I think it's stable.

If something goes wrong though, I will be notified through the OKAPI admin email reporting. For the case I am not timely available to fix it, you can safely hit the "revert" button for this commit.

This PR includes the commit of PR  #1162, i.e. it deletes lots of obsolete files which have accumulated due to a bug in automatic OKAPI deployment (and some more which I missed in the first commit).

### CODE REVIEW

**Comment by following5** [comment]
> This is an OKAPI refactoring

(transition to PSR-4, no functional changes)

**Comment by deg-pl** [comment]
@following5 Should be PR #1170 merged first?
Or this doesn't matter?

**Comment by following5** [comment]
Doesn't matter. If you merge this one, it will automatically close #1170.

**Comment by following5** [comment]
What I actually wanted to say:  If you merge #1170, it will automatically close #1162. :) The other way round, it will be two merges.

**Comment by following5** [comment]
I have closed the other PR, it is redundant.

Have also found the problem with OKAPI deployment, but still we must do this update manually because of synchronous change in the OCPL code (rename facade.php => Facade.php; didn't notice while testing because of NTFS file system).

**Comment by deg-pl** [comment]
@following5 CRITICAL: After merge this PR OKAPI doesn't work at all!
```
[Thu Sep 07 11:46:45.548273 2017] [:error] [pid 19141] [client 188.146.33.91:62681] PHP Fatal error:  Class 'okapi\\Settings' not found in /srv/ocpl/okapi/Okapi.php on line 445
[Thu Sep 07 11:46:45.548515 2017] [:error] [pid 19141] [client 188.146.33.91:62681] Class 'okapi\\Settings' not found
```

**Comment by following5** [comment]
I am looking into it.

**Pull request merged**
