### PR TITLE
Add translatio strings to GCT

### PR DESCRIPTION
**Pull request by andrixnet**
Fixes https://github.com/opencaching/opencaching-pl/issues/924

I know it may not be the most elegant solution, but apparently works :-)

### CODE REVIEW

**Comment by kojoty** [comment]
o it seem I commented this chanege in different PR here:
https://github.com/opencaching/opencaching-pl/pull/931/commits

**Comment by andrixnet** [comment]
Sorry, my baby was in the hospital for a few days and I couldn't tend to anything else. Will try to resolve soon.

**Comment by andrixnet** [comment]
I've cleaned up GCT.lang.php and also cleaned up the commits. 
@mzylowski please recheck and merge if ok. 
Thank you.

**Comment by mzylowski** [comment]
Will be merged after the weekend.

**Pull request merged**
