### PR TITLE
Update hu.php

### PR DESCRIPTION
**Pull request by kemist80**
Some hungarian translations

### CODE REVIEW

**Comment by harrieklomp** [comment]
@kemist80 
Thank you for your time to translate.
Please use https://crowdin.com/project/oc-polish-code-translations/hu# to translate to Hungarian. The system will do the rest to implement it in the code.

**Comment by kojoty** [comment]
@kemist80 
There is also quite nice tool from crowdin: translation in context where you can translate directly from the opencaching webpage - you can use it from your own dev. enviroment or from the real OC webpage - if you're interesting I can provide more details.

**Comment by kojoty** [comment]
we can't merge it - all translations must be done by crowdin.
I will try to move these phrases there.

**Comment by harrieklomp** [comment]
@kojoty  Translated lines are moved to Crowdin!

**Comment by kojoty** [comment]
cool, thanks @harrieklomp

**Pull request closed without merging**
