### PR TITLE
GPX attribute mapping overhaul; fixes #1242

### LINKED ISSUE #1242: GPX Attribute IDs conflict with OCDE IDs
I just noticed that the OCDE GPX attribute schema has been [adopted](https://github.com/opencaching/opencaching-pl/blob/d5bcc8a155d254c538cc1437afb9e0fe51b20906/lib/format.gpx.inc.php#L262) in OCPL code: Attributes which are not known to Groundspeak are added with ID +100 to the GPX file. It looks like this was added by @andrixnet in April 2017.

However, some of these IDs conflict with the IDs which are in use for years at Opencaching.de:

* 143: OCDE "Breeding season", OCPL "GeoHotel" (wrongly labeld as "Quick cache" [here](https://github.com/opencaching/opencaching-pl/blob/d5bcc8a155d254c538cc1437afb9e0fe51b20906/lib/format.gpx.inc.php#L276))
* 150 OCDE "Cave equipment", OCPL "Audio file"
* 153 OCDE "Aircraft required", OCPL "USB Dead Drop cache"
* 154 OCDE "Investigation", OCPL "Near a Survey Marker"

Then, there are these assignments with multiple conflicts:

OCDE 156 "Arithmetical problem":
* opencaching.ro/nl/uk 8 => 156 "Letterbox cache"
* opencaching.pl 56 => 156 "Letterbox cache"
* opencache.uk 156 => 156 "Aircraft required"

OCDE 157 "Other cache type":
* opencache.uk 57 => 157 "Other cache type":
* opencache.uk 157 => 157 "Rated on Handicaching.com"

OCDE 158 "Ask owner for start conditions":
* opencache.uk 58 => 158 "Ask owner for start conditions"
* opencache.uk 158 => 158 "Contains a Munzee"

This is a mess. It prevents adding the OCPL attributes to Okapi GPX using the [attrs=gc_ocde:attrs](https://www.opencaching.de/okapi/services/caches/formatters/gpx.html) option, and it prevents to write GPX tools which correctly process all Opencaching attributes. (I will add a second post with a proposal how to solve this.)

### PR DESCRIPTION
**Pull request by following5**
This implements a clean mapping of virtually ALL attributes used on OCPL-based sites to GPX attributes. Including the special attributes of Opencache.UK and Opencaching.US.

For the NL "Lost place" (see https://github.com/opencaching/okapi/issues/515) I have assumed that it is moved from ID 61 to 62. So this change retains the assignment of NL ID 61 to "Historic place" and adds 62 for "Lost place".

For the NL and RO "Bicycle" attribute (see https://github.com/opencaching/opencaching-pl/issues/1244) I have assumed that they mean "Accessible by bike" like at PL. This may need to be changed to a new attribute "Bicycle recommended", especially for RO which defined it as "Bicycle recommended" in native language.

Next step would be to add this mappings to Okapi, so that Okapi can produce the same GPX attribute IDs. Finally the mapping table here in format.gpx.inc.php may be replaced by a call to Okapi, so that all the mappings are kept only in one place.

(_Fun fact: The only attribute which is the same over all the sites - PL NL UK US RO - is "Flashlight required"._ :-)

### CODE REVIEW

**Comment by following5** [comment]
Compared to the current code, I have
* assigned new GPX IDs to about 10 attributes that conflicted with OCDE
* added lots of attributes that were missing due to conflicts between OCPL sites
* fixed a few wrong assignments
* added table-like comments that show which IDs are in use at which sites. Afaik this is the first complete overview of all OCPL-based atributes.

**Comment by andrixnet** [comment]
This summer I've been collaborating with Andy from OCUK on a cleanup of attributes for UK, which included many overlaps and also changing / adding / removing some of their attributes. Unfortunately due to available time constraints I wasn't able to finish this work properly. 

However here are the ideas I've been working on:
_together with your overhaul, they may make a better end result (also eliminate some of the code required to solve conflicts)_

**Comment by andrixnet** [comment]
[ocuk_attr.txt](https://github.com/opencaching/opencaching-pl/files/1354898/ocuk_attr.txt)

This is my overhaul of UK atributes, with clarifications to follow: 
-

**Comment by andrixnet** [comment]
[format.gpx.inc.zip](https://github.com/opencaching/opencaching-pl/files/1354957/format.gpx.inc.zip)
Not sure, but this may be an intermeediate step from my work this summer.

**Comment by andrixnet** [comment]
I had found a very good graphic for "millitary area" for UK, but I can't seem to locate the file right now. I shall return with it when I get it.

**Comment by andrixnet** [comment]
OCUS attribute changes: 
- DELETE "benchmark"
- DELETE "Munzee"
- DELETE "Offset cache"
- ADD "Challenge cache"
- Further info on english dialects: US favours "Quick cache". Same as "Park'n'grab" from GC and "Cache and Dash" from UK. 
Still don't know how to solve this. 


- "bring your children" = "Kid Friendly" = "recommneded for children" = "suitable for children" ? 
I think "suitable for children" would be best wording.
- "Big Rig Friendly" US specific, RV and trucker friendly
- "Snakes" is more specific then the generic "Dangeours animals". Perhaps should become it's own separate attrib.
- "Garmin Chirp" is "wireless beacon" on OCPL. I think "Wireless beacon" is better. (and allows for more radio based puzzles)
- "In the Woods" equivalent to "in nature", but mroe specific to inside forest. 
- "Historic Site" 
OCNL had at one time a confusion to which I propose the following: 
- 1. "Historic monument" - representing a building/site with historical significance"
- 2. "Ruin" - representing a derelict building/site as the state it is in, regardless of historical significance.
- "Limited Hours" = "NOT available 24/7"
- "Listed on OCNA Only" = "OC Only"
- "Contains Advertising" US attrib

**Comment by andrixnet** [comment]
I started remapping OCUK attribute IDs such that there is no longer any numerical overlap and make an SQL file specifically for OCUK to remap attributes both for the table definitions and existing cache <=> attrib mappings to the new IDs. 

The new IDs for OCUK remapping were to follow these rules: 
- all attribs present on UK and PL/NL/RO to have same ID (follow OCPL numbers)
- all attribs present on UK and DE but not PL/NL/RO to have same ID (follow OCDE numbers)
- all attribs present on UK with GC equivalent but no OC equivalent to have same ID (follow GC numbers)

Furthermore, as I have stated in format.gpx.inc tables of equivalence, 
- all OC specific (without a GC equivalent, or negated GC equivalent) to have IDs above 100
- all newer OC specific attribs to have IDs added only above 100

**Comment by andrixnet** [comment]
My appologies for listing all these here, I have done so hurriedly, trying to contribute as much as possible in the shortest available time.
Please move them to issues for me, if/where necessary.
Please feel free to use any of this for improving attrib handling.

I will return to continue my work on improving consistency later this month.

**Comment by following5** [comment]
My change does not conflict in any way with your ongoing efforts to optimize US and UK attributes. It just implements a clean mapping of all the currently existing attributes to GPX.

For the conflicting UK and US attributes I have added GPX mapping tables here: https://github.com/following5/opencaching-pl/blob/gpx-attribs/lib/format.gpx.inc.php#L327. The US table just pro forma, so that the US attribs are documented there and will be missed when changing other attributes.

If you succeed in resolving the UK and US conflict, these tables can be removed.

So I suggest to proceed here and fix the GPX issue now.

**Comment by following5** [comment]
My source was the original current contents of the `cache_attrib` tables of all the OC sites. It can be retrieved via Okapi:

* https://opencaching.pl/okapi/devel/attrlist
* http://www.opencaching.nl/okapi/devel/attrlist
* http://www.opencaching.ro/okapi/devel/attrlist
* http://opencache.uk/okapi/devel/attrlist

So these GPX new mapping tables are definitly up-to-date and correct.

**Comment by andrixnet** [comment]
Understood. Please proceed.

**Comment by kojoty** [comment]
@following5, can we merge this PR or there is anything more to do?

**Comment by following5** [comment]
This is ready for merge.

**Comment by kojoty** [comment]
Thanks @following5 !

**Pull request merged**
