### PR TITLE
Prevent adoption in some cases. 

### PR DESCRIPTION
**Pull request by mzylowski**
Related with #628

@andrixnet @harrieklomp I need one line translation - it can be posted even here as comment (if you don't have time for commit ;])

/cc @deg-pl @brasiaPL

### CODE REVIEW

**Comment by harrieklomp** [comment]
Because my 2 month old laptop is defect i cannot do it via commit for the next 3 or 4 weeks. When this is committed i can add the translation online.
Or if possible it also can be done via this commit.

'adopt_34' => 'Helaas kan deze gebruiker niet de nieuwe eigenaar worden van deze cache.',

**Comment by kojoty** [comment]
@mzylowski, I've worked on refactoring of adoption procedure for many days. This issue was assigned to me. You reassigned it to yourself without asking me about that. My changes are almost ready and are wider than yours. If you commit it I will need to merge many changes from your code.

My current changes are here: [(https://github.com/kojoty/opencaching-pl/tree/adoption_refactoring )]

Czarodziej,
If you want to fix issue which is assigned to someone else please ask such person about this and start your works when that person confirms it is OK for him/her - otherwise someone needs waste time :(

**Comment by mzylowski** [comment]
Of course your solution is better - it is full refactoring.

**Comment by kojoty** [comment]
@mzylowski thx :)

**Pull request closed without merging**
