### PR TITLE
#120: WITHIN is now synonim of MBRWITHIN in mysql so ST_WITHIN should…

### PR DESCRIPTION
**Pull request by kojoty**
… be used instead of that + changes in context of update nuts_* data

### CODE REVIEW

**Comment by kojoty** [comment]
@andrixnet, @harrieklomp 
This PR is waiting for all nodes to apply nuts_* data update from #120 
Please give me know here when your nodes will be ready... 

@deg-pl would you prepare ocpl db?

**Comment by deg-pl** [comment]
OC PL - done
OC UK - done
my devel - done :)

**Comment by andrixnet** [comment]
cache_location.class.php must also be updated with `ST_WITHIN`

**Comment by andrixnet** [comment]
OCRO has updated NUTS data.

**Comment by andrixnet** [comment]
Damn it, my mistake. Missed it. Sorry :-(

**Comment by andrixnet** [comment]
OCNL ready according to https://github.com/opencaching/opencaching-pl/issues/120#issuecomment-258160654

**Comment by harrieklomp** [comment]
Perhaps this is the wrong place but this is about NUTS. Yesterday there was this commit. OCNL DB was correct updated (i think) but from then there are every half hour a error.

+++ PDO Error +++ 

+++ Debug: Query: SELECT `level`, `code`, AsText(`shape`) AS `geometry` FROM `nuts_layer`

        WHERE ST_WITHIN(GeomFromText( ? ), `shape`)

        ORDER BY `level` DESC

+++ Ex_Code: 42000

+++ Ex_Msg: SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION ocnl4.ST_WITHIN does not exist

+++ Ex_Trace:

#0 /var/www/www.opencaching.nl/Utils/Database/XDb.php(117): PDOStatement->execute(Array)

#1 /var/www/www.opencaching.nl/util.sec/cache_locations/cache_location.class.php(53): Utils\Database\XDb::xSql('SELECT `level`,...', 'POINT(5.3206 51...')

#2 {main}

Can someone please advice me what goes wrong on OCNL?
Thanks.

**Comment by deg-pl** [comment]
@harrieklomp You have old MySQL server (ver. 5.5.30). ST_WITHIN was added from version 5.6.1. Could you upgrade your server? Old WITHIN has now "deprecaded" status  in MySQL.

OC PL uses MySQL v. 5.7.16
OC RO uses also old version of MariaDB - 5.5.43, but support for ST_WITHIN was from MariaDB v. 5.3.3
OC UK uses MariaDB v. 10.0.27

**Comment by harrieklomp** [comment]
I am not that technical :-(
I hope @andrixnet can make some time to fix or update this.

**Comment by andrixnet** [comment]
OCRO running on 5.5.53-MariaDB (upgrade according to distro security updates; updated today).

@harrieklomp I will try to take a look at your server on saturday

**Comment by andrixnet** [comment]
OCNL upgraded to MySQL-5.7.16 and running.

**Comment by andrixnet** [comment]
with database correctly containing polygons for regions and using st_within, this function may be obsoleted: ptInLineRing

**Pull request merged**
