### PR TITLE
#1430 issue fix

### PR DESCRIPTION
**Pull request by rapotek**
Executed on dev. before indentation was corrected, so please check if it makes sense and there are no errors.

### CODE REVIEW

**Comment by kojoty** [comment]
This is OK at my knowledge. Thanks @rapotek.

@deg-pl, @andrixnet, @harrieklomp:
please apply this sqlalter.

**Comment by deg-pl** [comment]
Done on OC PL and OC UK.
Thanks @rapotek

**Comment by harrieklomp** [comment]
Done on OCNL

**Comment by andrixnet** [comment]
done at OCRO

**Pull request merged**
