### PR TITLE
Add OKAPI signalling cronjob

### PR DESCRIPTION
**Pull request by following5**
This is a proposal to fix https://github.com/opencaching/okapi/issues/552 - update merit badges when users submit OKAPI logs. Also, it prepares editing cache coordinates via OKAPI, by doing the altitude calculation. And allows to add future "OKAPI->OCPL housekeeping" jobs.

Advantages:
* No redundant logic in OKAPI for merit badges etc.
* No code dependencies - if OCPL developers want to change the MeritBadgeController interface, this can be done independently from OKAPI code.
* Allows to change cache coordinates without having to wait for the external altitude provider. (This feature could also be provided via Facade, if needed.)

Disadvantages:
* The changes are not updated immediately, but with a time lag of some minutes by a cronjob.

The OKAPI side is already implemented and active. At OCPL sites, the following cronjob would be added:

`*/5 * * * * php /var/www/html/ocpl/util.sec/okapi/okapi_cronjob.php`
(or wherever the file is located.)

OKAPI stores the update reqests e.g. for merit badges in the `okapi_signals` table, and the new OCPL `OkapiController` cronjob reads and executes them.

### CODE REVIEW

**Comment by deg-pl** [comment]
@following5 We have SimpleRouter - your code can be reached by /Cron.Okapi/ - without calling  util.sec/okapi/okapi_cronjob.php

**Comment by kojoty** [comment]
@deg-pl do you have a time to look at this (if not just give me know please)...

**Comment by deg-pl** [comment]
@following5 sorry for my comment 2 weeks ago. You did it correctly.

Please update /docs/crontabs/cron-job-list yet.

**Comment by following5** [comment]
done

**Comment by deg-pl** [comment]
@andrixnet @harrieklomp There is a change in crontab - one additional job. Even if you don't use merit badges, you should add this to cron because of engine to update caches altitiude after changes in OKAPI.

**Comment by harrieklomp** [comment]
Added cronjob on OC NL

**Pull request merged**
