### PR TITLE
New Cronjob Engine

### PR DESCRIPTION
**Pull request by following5**
This implements a universal cronjob engine, as proposed in #1254. Implements all timing variants as requested by @deg-pl in #1254. The engine is located in `Controllers/Cron/CronJobController.php`, plus some job base classes in the subdirectory `Jobs`.

I have refactored (and tested) seven jobs into the new engine, so there are six less crontab entries after this change.
* publish caches (`run_publish`=> `PublishCachesJob`)
* new cache notification (`run_notify` => `NewCachesNotifyJob`)
* watchlist notification (`runwatch` => `WatchlistNotifyJob`)
* autoarchive caches (`auto_arch` => `AutoArchiveCachesJob`)
* fetch new geokrets (`geokrety.new` => `GeoKretyNewJob`)
* geokrety logging (`processGeoKretyDbQueue` => `GeoKretyDbQueueJob`)
* geopaths (`PowerTrailCronJob` => `GeoPathJob`)

The new OKAPI signalling job (#1769) is NOT refactored; it stays separate for performance reasons (slow external providers for the cache altitudes). So this PR does not affect #1769.

Also, I did not refactor `cache_titled_add.php`, which looks like a construction site.

The engine allows to
* disable single jobs per OC site (via settings.inc.php)
* run single jobs for testing (via util.sec/cron/run_cron.php + job name).

The intervals/times when the jobs are run are hard-coded; I tooke the times from `cron-job-list`. If different OC sites need different times, I can add config settings for that.

**Instructions for deploying this:**
* disable all the seven cronjobs listed above on ALL four OC sites
* merge this
* run the **sqlAlter**
* install the new cronjob engine, as shown in `cron-job-list`

(Alternatively, I could temporarily re-add the old cron job scripts. Then you could deploy this site by site; and when all four are done, the scripts can be removed again.)

Please priorize this as it fits your needs and time. It's not urgent for me in any way.

### CODE REVIEW

**Comment by deg-pl** [comment]
@following5 Yours work is awesome!
BUT :)
1) We can't disable cronjobs on all 4 OC PL sites till merge. It is impossible. Please revert all old cronjobs - we'll deploy new cronjob engine site by site.
2) cache_titled_add.php on OC PL we run weekly, on OC UK and OC NL monthly, and on OC RO isn't run at all. Can we migrate this script into new cronjob engine, but with posibility to configure running interval per site?

**Comment by deg-pl** [comment]
@following5 It is great! Very good job.
But... (please, don't kill me ;) ) settings.inc.php is our obsolete system. Cron engine config should be in /Config directory - see files included in this directory.
So... could you once more refactor your code?

**Comment by kojoty** [comment]
> @following5 It is great! Very good job.
> But... (please, don't kill me ;) ) settings.inc.php is our obsolete system. Cron engine config should be in /Config directory - see files included in this directory.
> So... could you once more refactor your code?

I agree - we definitely would like one day to remove the "settings.inc.php" at all.

**Comment by following5** [comment]
Nice. Have refactored the config. Please verify the schedule im Config/cronjobs.* for other sites than PL.

But how can I overload the settings now on my devel site? E.g. I want to disable the GeoKrety job:

`$cronjobs['schedule']['GeoKretyNewJob'] = 'disabled';`

**Comment by following5** [comment]
When everything is ok, I would squash this all into one commit. Don't think the inbetween iterations are relevant in any way.

**Comment by following5** [comment]
Have found a way to move the Okapi Signalling cronjob into the new cron engine. So _all 9_ OCPL cronjobs are now included here. Sorry for the duplicate work with updating the crontab ... I did not expect that this would work.

**Comment by kojoty** [comment]
@deg-pl , @following5 

I don't have more comments for now - lets merge it. I assume that cron jobs are just copied - I don't try to compare the differences and the content of jobs.

I think it would be great to make a few minor changes/improvements - but let's do that later - not in one commit:

- removing util.sec/cron/run_cron.php at all - if we have a central cron class we don't need this - we can call that class directly - of course it needs small refactor to allowing call by local only

- trivial: obsoleted "jobs" scripts can be removed

I don't know if anyone of us check regular how the cron works so:
- it would be great to add simple way to check the cron results for "tech-admin" menu
- it would be great to add email alert sending on any error in cron 

Best regards from far...
kojoty

**Comment by following5** [comment]
I have squashed the commits and fixed the Jobs paths.

> I assume that cron jobs are just copied

There are a few adjustments regarding Locks and error handling.

> it would be great to add email alert sending on any error in cron

This should already work, at least on my develsite it does. In case of error, a message is output to stderr or stdout. The cron daemon then sends an email to root.

**Comment by following5** [comment]
Btw, when the new cron engine runs for the first time, it will not know the last run time of the jobs, and immediately run all jobs that may be overdue. From the second run, everything will run at the scheduled times.

**Comment by deg-pl** [comment]
Is any way to overide this? For job which select cache of the week/month

**Comment by following5** [comment]
It's okay for this job, because it is configured for a certain day of week or month. Will not run on any other day, and not before 21:55.

When should that job run on NL and UK sites? I configured it for day one at 21:55, i.e. next run on 1 January 21:55.

**Comment by harrieklomp** [comment]
On OCNL we have 0  0  1  *  *
When i am correct first day of the month at 00:00
It can be changed later that night if needed.

**Comment by following5** [comment]
Ok. I move it to 0:20, so there is better load distribution of cronjobs.

**Comment by deg-pl** [comment]
@andrixnet We have new crontab engine made by following. To migrate to new engine switch off all current crontab jobs (except OKAPI cron5 and DB maintenance jobs) and add one job which should be done every 5 minutes - see /docs/crontabs/cron-job-list

@harrieklomp - I think you already use new engine ;)

**Comment by harrieklomp** [comment]
@deg-pl Yes OCNL is running with new engine.

**Pull request merged**
