### PR TITLE
Ui

### PR DESCRIPTION
**Pull request by mzylowski**

### CODE REVIEW

**Comment by mzylowski** [comment]
Tested on my VM and on opencaching.nl
SUCCESS :)
selection_016
selection_015
selection_014
selection_013

**Comment by harrieklomp** [comment]
That looks great :+1: 
Than i wonder, When a Polish does register on oc.nl. Why does he get the Dutch translation? Is it more logic that he receives the mail in Polish language. The translations are available.
My opinion, use translation from selected country on registrationpage.

**Comment by deg-pl** [comment]
Całkiem fajne!
Proponuję zamianę: "Twoje 3 pierwsze skrzynki..." na "Twoje 3 pierwsze założone skrzynki..."

**Comment by mzylowski** [comment]
Oh snap... I posted pictures in the wrong PR discussion...
Sorry, I'm on lecture in my university.
Let's move this discussion to #478

**Pull request merged**
