### PR TITLE
formal cleanup of whitespaces, line ends and file ends

### PR DESCRIPTION
**Pull request by following5**
- resolve tabs to 4-char spaced columns
- remove whitespaces end of line
- change CR/LF line endings to LF
- remove PHP close tag at at end of file
- remove blank lines at end of file
- add missing LF to end of file

I can add the check script to the repo, but did not know in which directory it would go.

### CODE REVIEW

**Comment by kojoty** [comment]
Huge commits are my favorites :) 

> I can add the check script to the repo, but did not know in which directory it would go.

I have a proposal of folder structure:
https://github.com/opencaching/opencaching-pl/pull/1910

according to this let's add /bin folder and put it there :)

**Comment by following5** [comment]
/bin/devel/style-cleanup.php ?

**Comment by following5** [comment]
> This is a mistake.
> /** means PHPDoc not comment
> /* means comment
> And every line should have asterisk before text.

Sure. There probably are lots of other mistakes of this kind in the source code.

I can try to add PHPdoc fixing to the cleanup script.

**Comment by following5** [comment]
The CR/LF => LF fix has too many conflicts with open working branches. Have disabled that for now, and added phpDoc fix and cleanup script.

**Pull request merged**
