### PR TITLE
 	Fix conversion errors, improve performance

### PR DESCRIPTION
**Pull request by miklobit**
improve performance (DB import with low-end server)
 - limit data size per single INSERT
 - split schema import ( import data without triggers active )
convert binary data to hex 
remove all truncated data fields  (to get  reliable test data)

### CODE REVIEW

**Comment by andrixnet** [comment]
@miklobit what do you mean by "**low-end server**" ?

**Comment by miklobit** [comment]
Low-end = VPS with resources as low as 1xCPU/1GB RAM.
Finally i was able, with such  resources, to import (almost) complete PL database  in abt. ~30 min.

**Comment by andrixnet** [comment]
How many caches are there on OCPL (total), and how many log entries (these being the tables with most rows) ? 

Note: OCRO is running on VPS with 1CPU; 0.5GB RAM (as comparison, but our cache count doesn't compare :-) )

**Comment by deg-pl** [comment]
@andrixnet why you don't use Arubacloud VPS Small - 1 EUR/month (+VAT) gives you 1 core, 1GB RAM and 20GB SSD storage! https://www.arubacloud.com/vps/virtual-private-server-range.aspx

**Pull request merged**
