### PR TITLE
Medals cleanup

### PR DESCRIPTION
**Pull request by mzylowski**
After merging @tripper1971 badges solution we can throw away code related with previous try of medals module. Old medal system was never finished, and all work was abandoned.

### CODE REVIEW

**Comment by mzylowski** [comment]
@harrieklomp @andrixnet @deg-pl 
Please apply on your nodes: https://github.com/opencaching/opencaching-pl/blob/master/sqlAlters/2017-03-31_remove_medals.sql
PL node is done.

**Comment by deg-pl** [comment]
Done @ OC UK

**Comment by harrieklomp** [comment]
Done on oc.nl

**Comment by andrixnet** [comment]
Done @ OCRO, including 2017-03-30_merit_badges.sql

**Pull request merged**
