### PR TITLE
#764 some buttons, inputs, etc

### PR DESCRIPTION
**Pull request by DorotkaMakotka**
* search results - buttons etc
searchresults
savesearchresults

### CODE REVIEW

**Comment by DorotkaMakotka** [comment]
@harrieklomp, @andrixnet:
Hi, please note that there is a small translation change :) thanks!

**Comment by harrieklomp** [comment]
I will translate it after commit.

**Comment by andrixnet** [comment]
Same here, will translate after commit. (I have some more translations to check and update)

**Comment by andrixnet** [comment]
RO Translations updated in https://github.com/andrixnet/opencaching-pl/commit/b368bec0551354547b32c7708cdc62870825dddd

**Pull request merged**
