### PR TITLE
fix for #628 - adoption refactoring

### PR DESCRIPTION
**Pull request by kojoty**
This is almost full refactoring of adoption process + minor changes in template system: now there is a simple way to use PHP in templates for printing in loop, conditions etc.

### CODE REVIEW

**Comment by kojoty** [comment]
@mzylowski, please take a look at this:
- first if my changes have the same effect as your previous changes (maybe I miss something)
- second - I've skipped refactoring of email sending in context of adoption - can you do it later - you have an experience in email refactoring

@harrieklomp, @andrixnet: There are also a few translation changes - please take a look...

**Comment by harrieklomp** [comment]
After commit i will translate this.

**Comment by harrieklomp** [comment]
Perhaps there can be a line translated in Polish in http://www.opencaching.pl/openchecker.php in this commit.

selectie_004

**Comment by kojoty** [comment]
@harrieklomp I fix pl translation you mentioned here: #715

**Comment by mzylowski** [comment]
> first if my changes have the same effect as your previous changes (maybe I miss something)
It's even better :)

LGTM :+1:

**Comment by mzylowski** [comment]
ehh.. conflicts with #711 
Sorry.

**Comment by kojoty** [comment]
conflicts resolved - continuation in pull request #719

**Pull request closed without merging**
