### PR TITLE
Refactoring emails: part 3

### PR DESCRIPTION
**Pull request by mzylowski**
Relates with: #48 #490 

@andrixnet @harrieklomp @deg-pl 
This PR require config upgrade on nodes. For PL node it will be:
`$subject_prefix_for_site_mails = "OCPL";`
`$subject_prefix_for_reviewers_mails = "COG";`
@deg-pl please update our .../ocpl/lib/settings.inc.php :)

For details -> lib/settings-example.inc.php

Please let me know when yours nodes will be ready.

### CODE REVIEW

**Comment by deg-pl** [comment]
@mzylowski done. OCPL is ready ;)

**Comment by harrieklomp** [comment]
Done on OCNL

**Comment by andrixnet** [comment]
Done on OCRO. 

Note: it would've been better to create these settings along the line of development of  [`settingsDefault.inc.php`](https://github.com/andrixnet/opencaching-pl/blob/settings/lib/settingsDefault.inc.php), something like 
```
// Subject prefix for all emails.
$config['node']['mail']['prefix'] = 'OCPL';
// Subject prefix for admin/reviewer notifications
$config['node']['mail']['prefix_admin'] = 'COG';
```

**Comment by mzylowski** [comment]
Comitment from the train ;]

- Rebased to current master
- Email refactoring related with #713 #628 #719

@kojoty PTAL

**Pull request merged**
