### PR TITLE
#1547: custom favicons configured per node

### PR DESCRIPTION
**Pull request by kojoty**

### CODE REVIEW

**Comment by kojoty** [comment]
@harrieklomp, @andrixnet 
please note that after merging this you can add custom favicons for your nodes

**Comment by harrieklomp** [comment]
@kojoty 
Should file public/images/icons/site.nl.php not be in config map? :-)

**Comment by kojoty** [comment]
@harrieklomp, ups :) ech... night works

**Comment by kojoty** [comment]
@harrieklomp, if you have an access to git now, can you move the file to the right place or I will fix it tonight...

**Comment by harrieklomp** [comment]
@kojoty I will move the file to correct place.

**Pull request merged**
