### PR TITLE
New feeds engine

### PR DESCRIPTION
**Pull request by deg-pl**
New feeds engine can handle any quantity of feeds - i.e. one for blog and the second for newest forum posts. Supports both of RSS and Atom feeds. Should work faster than old engine.

@andrixnet @harrieklomp you should change your settings:
1) remove $config['blogMostRecentRecordsUrl'] and $BlogSwitchOn. But don't remove $blogsite_url - this is not related with feeds!

2) add to your settings.inc.php:
$config['feed']['enabled'] = array('blog');
$config['feed']['blog']['url'] = '{blog_feed_url}';

As {blog_feed_url} please insert URL of your blog feed. I think @andrixnet should have 'http://blog.opencaching.ro/feed/' and @harrieklomp - 'http://blog.opencaching.nl/?feed=rss2' or better 'http://blog.opencaching.nl/?feed=atom'

If you want display other than 5 numbers of newest post, add: 
$config['feed']['blog']['posts'] = 5;
(and change 5 to the other value)

If you don't want to show author of posts, add also:
$config['feed']['blog']['showAuthor'] = false;

@harrieklomp may also enable feeds for his forum. Example configuration:
$config['feed']['enabled'] = array('forum', 'blog');
$config['feed']['forum']['url'] = 'http://forum.opencaching.nl/feed.php';
$config['feed']['blog']['url'] = 'http://blog.opencaching.nl/?feed=atom';

3) run l/tpl/stdstyle/etc/write_newblogs.inc.php to generate new files with feeds entries. This script also should be called by cron, but I think you have it already.

4) delete unused file $dynstylepath/start_newblogs.inc.php (maybe /srv/ocpl-data/tpl/stdstyle/html/start_newblogs.inc.php?)

Done ;)

### CODE REVIEW

**Comment by deg-pl** [comment]
@andrixnet you have a problem with OC RO. Server seems to be switched off. Github failed do webhook, so you have old RSS engine. You should first fetch code i.e. via http://www.opencaching.ro/post-commit.php

**Comment by andrixnet** [comment]
I am having some connectivity issues that I escalated to my ISP. Tomorrow I will handle the rest. 

Thank you.

**Comment by harrieklomp** [comment]
@deg-pl 
Thanks for this great future and the extra explanation :+1: 
Done on OCNL including some translations

**Comment by deg-pl** [comment]
I've forgot to write that you should change translations ;) thanks @harrieklomp ;)
@andrixnet - please verify feed_blog translation and translate feed_forum.

**Comment by andrixnet** [comment]
I've had updates switched off for a while, as the code stayed on my well_defined branch. (see my repository). I've been adding updates manually. 
This is while I work on the cache sizes issues (nano works on OCRO, but code is yet incomplete). 

Anyway, we're not displaying feeds (at this time) on homepage)
But I've taken into account the new features and modifications. 
Thank you. 

Translations verified.

**Pull request merged**
