### PR TITLE
Some site speed optimizations

### PR DESCRIPTION
**Pull request by deg-pl**
**OC PL now (HTTP/2 + PHP 7.1 + https):**
image

**After merge this PR & some Apache config tuning:**
image

**OC DE :)**
image
Source: https://developers.google.com/speed/pagespeed/insights/

### CODE REVIEW

**Comment by deg-pl** [comment]
Proposed Apache config change:

```
FileETag MTime Size

# EXPIRE HEADERS
<IfModule mod_expires.c>
  # Turn on the module.
  ExpiresActive on

  # Set the default expiry times.
  ExpiresDefault "access plus 1 day"

  ExpiresByType image/jpg "access plus 1 month"
  ExpiresByType image/gif "access plus 1 month"
  ExpiresByType image/jpeg "access plus 1 month"
  ExpiresByType image/png "access plus 1 month"
  ExpiresByType text/css "access plus 1 month"
  ExpiresByType text/javascript "access plus 1 month"
  ExpiresByType application/javascript "access plus 1 month"
  ExpiresByType text/css "now plus 1 month"
  ExpiresByType image/ico "access plus 1 month"
  ExpiresByType image/x-icon "access plus 1 month"
  ExpiresByType text/html "access plus 600 seconds"
</IfModule>

# CACHE-CONTROL HEADERS
<IfModule mod_headers.c>
  <FilesMatch "\\.(ico|jpe?g|png|gif|swf|gz|ttf|svg)$">
    Header set Cache-Control "max-age=2628000, public"
  </FilesMatch>
  <FilesMatch "\\.(css)$">
    Header set Cache-Control "max-age=2628000, private"
  </FilesMatch>
  <FilesMatch "\\.(js)$">
    Header set Cache-Control "max-age=2628000, private"
  </FilesMatch>
  <FilesMatch "\\.(html|htm)$">
    Header set Cache-Control "max-age=86400, public"
  </filesMatch>
  <FilesMatch "\.(pl|php|cgi|spl|scgi|fcgi)$">
    # Header set Cache-Control "max-age=600, private, must-revalidate"
    Header unset Cache-Control
  </FilesMatch>
</IfModule>

#Compression
<IfModule mod_deflate.c>
  AddType image/svg+xml .svg
  AddOutputFilterByType DEFLATE image/svg+xml
  AddOutputFilterByType DEFLATE text/plain
  AddOutputFilterByType DEFLATE text/html
  AddOutputFilterByType DEFLATE text/css
  AddOutputFilterByType DEFLATE text/javascript application/x-javascript application/javascript
</IfModule>
```

Of course modules: expiries, headers and deflate should be enabled first.

**Comment by kojoty** [comment]
Let me know what was changed in these images (Ciekawy jestem).

**Comment by deg-pl** [comment]
Size only ;)

**Comment by andrixnet** [comment]
@deg-pl proposed changes are for root dir .htaccess (IMO) or for virtualhost config file?

**Comment by deg-pl** [comment]
@andrixnet best place is virtualhost config file. This file is readed only once - on Apache startup. htaccess is read at every request. So better way is to give this settings to virtual host config.

**Pull request merged**
