### PR TITLE
#732 fix: Add new column in viewpendings (last log)

### PR DESCRIPTION
**Pull request by DorotkaMakotka**

### CODE REVIEW

**Comment by DorotkaMakotka** [comment]
Quick fix for #733.

**Comment by kojoty** [comment]
@harrieklomp, @andrixnet there is a small translation change but it can be seen only by admins

**Comment by harrieklomp** [comment]
I will translate it after commit.

**Comment by DorotkaMakotka** [comment]
+ #734 (Highlight 'forgotten' pendings/reports)

**Pull request merged**
