### PR TITLE
Improved ocpl-update.extended.sh (update script).

### PR DESCRIPTION
**Pull request by andrixnet**
* Features:
- OPENCACHING-PL website files owned by designated (non-root) unix user
- select branch to sync to (default: master)

* Sysadmin options:
- log each update to syslog
- select log facility (default cron.info -> /var/log/cron)
- keep local changes between updates, if really necessary
- show modified files by update operation

### CODE REVIEW

**Comment by mzylowski** [comment]
I'm no so much experienced in ocpl automation mechanism to review this PR.
Somebody else? ;]

**Comment by kojoty** [comment]
@andrixnet can you explain in a few words how/when/why we uses this script?

**Comment by andrixnet** [comment]
This is an administrative extension to the basic update script suggested by wrygiel after the move to github.

It allows: 
- simple update of the website
or
- configurabile administrative actions: 

1. log to syslog on every update; configurable log channel and level
Allow sysadmin to see update history and potentially track problems with the updates on that server
2. option to protect local changes from being overwritten. 
Example: preserve modified .htaccess until #105 and #508 are solved
3. option to include list of modified files when logging each update.
4. perform all actions in a unified configurable way. Only need to edit config variables.

I have applied a similar script with SVN while at google code and it helped me greatly (as sysadmin) to track down and fix some inconsistencies and locally broken update process.

It also makes good system administration practice, to keep track of changes to your server.

**Comment by andrixnet** [comment]
One needs to set SITE_NAME, SITE_USER, REPO and BRANCH to proper values.
Having DO_LOG=0 and KEEP_LOCAL=0 makes the script behave like the simple update script as first deployed with github.

**Pull request merged**
