### PR TITLE
NUTS data

### PR DESCRIPTION
**Pull request by andrixnet**
I have added NUTS data to the repository /docs 
(make it available for new installations). 

Data according to updates here : https://github.com/opencaching/opencaching-pl/issues/120
Data provided by @kojoty from NUTS_2013
UK->GB changes applied.

SQL file now contains "DROP TABLE" statement to make sure this data replaces old one.

### CODE REVIEW

**Comment by deg-pl** [comment]
@andrixnet we should fix util.sec/cache_locations/cache_location.class.php. I.e.:
use Utils\Gis; should be use Utils\Gis\Gis;

Code:
`        $sCountry = XDb::xSimpleQueryValue(
            "SELECT `countries`.`pl` FROM `caches`
            INNER JOIN `countries` ON `caches`.`country`=`countries`.`short`
            WHERE `caches`.`cache_id`='$rCache[cache_id]'", 0);`
will load POLISH names of countries!

**Comment by andrixnet** [comment]
Have to update with PL names, to have a consistent and up to date version

**Comment by kojoty** [comment]
@andrixnet, @deg - what is with this PR - can we merge it or close it?

**Comment by deg-pl** [comment]
@kojoty I don't know. Ask Andrixnet ;)

**Comment by harrieklomp** [comment]
Andrixnet is on vacation at this moment. I believe he is back next week.

**Comment by deg** [comment]
Please drop me from these conversations. I think you have confused me with someone else repeatedly.


Sent from my phone, +972 54 723-0120
Please excuse my auto-correct eras.




On Tue, Jul 18, 2017 at 6:44 PM +0200, "kojoty" <notifications@github.com<mailto:notifications@github.com>> wrote:


@andrixnet<https://github.com/andrixnet>, @deg<https://github.com/deg> - what is with this PR - can we merge it or close it?

**Comment by andrixnet** [comment]
I'll recheck soon, I'm back and I'm trying to catch up.

**Comment by andrixnet** [comment]
Won't merge this as I will (re)process NUTS data with new information from @deg-pl and will try to include US data as well.

**Pull request closed without merging**
