### PR TITLE
Total news system refactoring (from scratch)

### PR DESCRIPTION
**Pull request by deg-pl**

### CODE REVIEW

**Comment by deg-pl** [comment]
@andrixnet @harrieklomp This is a new news system. Please do included sqlAlter. System is compatibile with old database format, but news management is disabled till sqlAlter. Has many new features - more information soon ;)

Please - do proper translations. This is not critical, because users will see two short strings. All other are shown only to admins.

**Comment by kojoty** [comment]
yeah!

**Comment by harrieklomp** [comment]
OCNL did run the sql alter and it works perfect. The translations will be done tomorrow after my night shift.
Great work!!!!

**Comment by deg-pl** [comment]
@harrieklomp @andrixnet You should also remove from yours settings.inc.php obsolete:
```
$use_news_approving
$news_approver_email
```

**Comment by harrieklomp** [comment]
Removed on OCNL

**Comment by andrixnet** [comment]
done at OCRO

**Pull request merged**
