### PR TITLE
use same page for all 'my logs' lists

### PR DESCRIPTION
**Pull request by following5**
This fixes issue #1709. It does the same also for 'Attended' and 'Moved' Logs.

But why are the logs sorted primarily by date_created? Wouldn't it be more useful to sort them by date of log?

### CODE REVIEW

**Comment by following5** [comment]
Added fix for #1694 and then noticed that @deg-pl has assigned that issue. I hope there is no big conflict of this PR to ongoing user profile refactoring? It changes/adds five links in viewprofile.php.

**Comment by kojoty** [comment]
@following5 can you please resolve conflicts for this PR...

**Comment by following5** [comment]
Done. Conflict was in deleted file my_logsFind.php.

**Comment by kojoty** [comment]
Thanks!

**Pull request merged**
