### PR TITLE
renamed OKAPI settings and facade files

### PR DESCRIPTION
**Pull request by following5**

### CODE REVIEW

**Comment by deg-pl** [comment]
@following5 Yeah! It works without errors! Thanks! ;)

**Comment by following5** [comment]
Okay, I will now try to reanimate the automatic OKAPI deployment.

@deg-pl 
I did not receive any error messages, though I am in the OKAPI admin email list: https://github.com/opencaching/opencaching-pl/commit/dae37b039b14739f4958a493a0b31b8824c5a96f (The address works, also checked the spam folder). Did you receive the error notification mails?

**Comment by following5** [comment]
Oh dear - if the settings are broken, OKAPI does not know the admin email addresses because they are in the settings. :-)

**Comment by teiling88** [comment]
thank you for your work @following5 :+1:

**Pull request merged**
