### PR TITLE
Add size Nano cache to GeoPath

### PR DESCRIPTION
**Pull request by harrieklomp**
Add size Nano cache to show in GeoPath statistics when this cache size is in a GeoPath.
Please check if all is correct and merge.
See also #2066

### CODE REVIEW

**Comment by harrieklomp** [comment]
I do like to make a suggestion before merge this PR.

Could it be possible to hide cache size when there is not such cache size in GeoPath?
Selectie_366

**Comment by kojoty** [comment]
> 
> Could it be possible to hide cache size when there is not such cache size in GeoPath?

Yes, this is quite simple - let me update your PR this evening.

(Sorry for the late response - I'm totally out of time, and I afraid there is no much chance for change to the end of August - lots of professional work last weeks + vacation without computer).

**Comment by kojoty** [comment]
quick update: not "this evening" but "tomorrow morning" :)

**Comment by kojoty** [comment]
> quick update: not "this evening" but "tomorrow morning" :)

unfortunately work still "in progress" but I'm working on this now :)

**Comment by kojoty** [comment]
OK, in my opinion it's ready now - please test and merge if looks OK for you :)

**Pull request merged**
