### PR TITLE
New waypoint "Trailhead"

### PR DESCRIPTION
**Pull request by harrieklomp**
Please first run https://github.com/opencaching/opencaching-pl/commit/bc905ec2700fb3c8e4a4f7b3f14f25d3a2640ac8#diff-39efba7ef4f4f22331aa8da5b1f6da49
Here are some changes that should add the waypoint "Trailhead" to the list of other waypoints.
Please check if everything is correct.

### CODE REVIEW

**Comment by harrieklomp** [comment]
DB on oc.nl has been updated with this new waypoint.

**Comment by harrieklomp** [comment]
From other notifications it shows that OCRO has updated their DB.
OCPL  and OCUK has no "ro" and "de" in the database. Will this be added to Polish and UK DB?

**Comment by deg-pl** [comment]
@harrieklomp could you send me your full export of waypoint table?

**Comment by andrixnet** [comment]
Please use this PR instead: https://github.com/opencaching/opencaching-pl/pull/990

**Pull request closed without merging**
