### PR TITLE
fix for #1080 - user message is no longer stored in DB

### PR DESCRIPTION
**Pull request by kojoty**
this change is in context #1080

### CODE REVIEW

**Comment by kojoty** [comment]
@deg-pl, @andrixnet, @harrieklomp - please note new sqlalter from this PR

**Comment by deg-pl** [comment]
Done on OC PL and OC UK

**Comment by harrieklomp** [comment]
Done on OCNL

**Comment by andrixnet** [comment]
Done on OCRO.

**Pull request merged**
