### PR TITLE
Do not touch images smaller then 100kb #275

### PR DESCRIPTION
**Pull request by mzylowski**
When file is smaller then 100kb we accept them and just save on the server.

It was difficult to test it on VM. I think we need additional test it before merge.

### CODE REVIEW

**Comment by kojoty** [comment]
@mzylowski, it seems that this change should be also done in files: editpic and newpic-gps..
- just locate places where SimpleImage is used to resize

**Comment by mzylowski** [comment]
Oh, sorry. I think in the futher we need one interface for putting picure on the server. :)

**Comment by andrixnet** [comment]
The same changes should also be applied here: 
newpic-gps.php
editpic.php

**Comment by andrixnet** [comment]
@mzylowski your suggestion is good. Please create an issue about it.

**Pull request merged**
