### PR TITLE
Next step to the layout refactoring - MENU!

### PR DESCRIPTION
**Pull request by kojoty**
Hi,

@andrixnet, @harrieklomp, @deg-pl - please take a look - this PR contains important changes, which probably need your node config update!

I've made complete menu refactoring and now:

- menu configuration is ready for customizing - every node can change all menus (horizontalBar, footerMenu and sideBar-main-menu, sideBar-admin-menu, sideBar-user-menu ) - customization is possible by config files in /Config/Menu 

- How menu generation works now (in short words):
  - script is looking for `<kind-of-menu>.local.php` file - if it is found this file is used for menu gen.
  - if there is no such file `<menu-name>.<ocNode>.ph`p file is loaded and used
  - if there is no such file `<menu-name>.default.php` file is used for menu gen.

  **- fill free to add your node-menu-configs to this PR**

- There are also similar files for links config - `/Config/link.default.php` / `links.pl.php` - it contains links used in many places in the code - **please temporary leave links configs in your `settings.inc.php` but please create and fill your node-specific links config**

- I change order of default menu - please take a look - I hope this is more "logical" - but please let me know if I've made it wrong :)

I'm waiting for your review and comments and I'll merge it if all of you agree :)

### CODE REVIEW

**Comment by kojoty** [comment]
image
old sidebar vs new sidebar (this is not a final version - this is just first cleanup)

**Comment by kojoty** [comment]
image

and may default sidebar for non-authorized view

**Comment by harrieklomp** [comment]
Please before commit. Change http://www.flopp-caching.de to https://flopp-caching.de in Config/Menu/customUserMenu.default.php because the old link is not working anymore on OC nodes at this moment.

**Comment by kojoty** [comment]
> ... Change http://www.flopp-caching.de to https://flopp-caching.de in Config/Menu/customUserMenu.default.php because the old link is not working anymore

done - Thanks Harrie.

**Comment by harrieklomp** [comment]
Please also add a "s" to http. Should be https. :-)

**Comment by kojoty** [comment]
> Please also add a "s" to http. Should be https. :-)

done :)

**Comment by kojoty** [comment]
@andrixnet, @deg-pl, @harrieklomp  - I just reminder - please review it - especially links and menu configuration and prepare your own custom menus if necessary (if defaults are not what you want to see at your node). If you don't have a time please send me your settings.inc.php (of course first remove  sensitive data like passwords and keys) and then I review your local settings and prepare configs which get the same effect.

If you are ready for commit this change let me know here as well.

Thanks!

**Comment by andrixnet** [comment]
OCRO settings file sent.

**Comment by deg-pl** [comment]
@kojoty Napłodziłeś tego kodu tyle, że nie mam czasu, aby dobrze się przyjrzeć. :)
Śmiało zmieniaj co Ci tylko w settingsach pasuje. Ja w wolnej chwili zobaczę do Twoich zmian, ale z racji ich rozległości - zabierze mi to sporo czasu.

**Comment by kojoty** [comment]
OK, I've prepared all necessary config for all nodes (ro/nl/uk/pl) and in my opinion this PR is ready to merge. Please be awared that this PR changes the menu a little (especially the order of sidebar menu options) - please see this screenshot:
image

here is "main menu" in two versions: for authorized and non-authorized user + user-menu with all my-<something> + something new "additional menu" or "extra menu" - the place when I put all less important options which were listed in menu till now.

@andrixnet , @harrieklomp , @deg-pl Please let me know if this si OK for you and I can merge it.

**Comment by andrixnet** [comment]
The "additional menu" might also be called "user's tools" or something similar. 
It does look like a collection of tools. 

From my perspective: great job!

**Comment by harrieklomp** [comment]
This looks very good 
Thanks :+1:

**Comment by harrieklomp** [comment]
Could it be possible to also remove the "www." from the Floppsmap link? ;-)

**Comment by kojoty** [comment]
> Could it be possible to also remove the "www." from the Floppsmap link? ;-)

@harrieklomp, feel free to commit such change if you think this is right :)
There is also some translation needed (at least around new name for cachemap-v2).

**Comment by kojoty** [comment]
@harrieklomp - flopps map link is here: https://github.com/opencaching/opencaching-pl/blob/master/Config/Menu/additionalPages.default.php feel free t remove it from OPCL config as well (here: https://github.com/opencaching/opencaching-pl/blob/master/Config/Menu/additionalPages.pl.php)

**Comment by harrieklomp** [comment]
I will do that. 
Thanks.

**Pull request merged**
