### PR TITLE
update okapi notification mail addresses

### PR DESCRIPTION
**Pull request by following5**
I have quit Opencaching development.

### CODE REVIEW

**Comment by mzylowski** [comment]
@following5 it is very sad info. Can I ask you, why?

**Comment by following5** [comment]
Things are happening at Opencaching.de which I can neither accept nor change, so it's time to leave.

**Comment by mzylowski** [comment]
:(
We will miss you!
Thanks for your contribution!

**Comment by mzylowski** [comment]
cc @opencaching/opencaching-pl-lead-programmers

**Comment by kojoty** [comment]
I agree it's sad. @following5 great thanks for all your hard work for our community! I hope it's a break not the end!

**Comment by wloczynutka** [comment]
@following5, you are still welcome to work with us on our international opencaching code. Our master branch code is used in countries: PL, NL, B, L, RO, and older versions in USA, JP and UK. Maybe some day we will be able to sync databases, to give international opencaching comunity green light to play international.

Anyway It was pleasure to cooperate with you. I hope you chenge your mind, (if nto today, maybe in future) and stay with our international team ;)

best regards.

**Comment by andrixnet** [comment]
@following5 thank you very much for your contributions to our community.
Best regards.

**Pull request merged**
