### PR TITLE
Updated .htaccess for site aliases redirection moved to server config.

### PR DESCRIPTION
**Pull request by andrixnet**
Changes to .htaccess to make it independent of hostname.
Fixes https://github.com/opencaching/opencaching-pl/issues/105 for all current nodes.
OC NL = ready
OC RO = ready
OC PL = pending, new server and configs by @wrygiel

### CODE REVIEW

**Comment by andrixnet** [comment]
This should only be merged after OC PL website is ready. 
That means either current website config is updated and this is merged, 
or
New website is configured accordingly and this is merged when the new website enters service.

**Comment by deg-pl** [comment]
@wrygiel - could you change Apache config at old OC PL server too? And then merge ;)

**Comment by wrygiel** [comment]
You mean, add this?

```
<VirtualHost *:80>
    ServerName www.opencaching.pl
    Redirect / http://opencaching.pl/
</VirtualHost>
```

Ok!

**Comment by wrygiel** [comment]
Done.

**Comment by deg-pl** [comment]
@wrygiel W pierwszym virtualhost zmień proszę www.opencaching.pl na opencaching.pl, z ServerAlias usuń opencaching.pl
Innymi słowy początek pliku ocpl powinien wyglądać tak:
```
<VirtualHost *>

        ServerName      opencaching.pl
        ServerAlias     test.opencaching.pl
```
Wtedy przeładuj Apache i możesz mergować ;)

**Comment by deg-pl** [comment]
W zasadzie ten ServerAlias też można wywalić - test.opencaching.pl nie jest do niczego wykorzystywany i wskazuje dokładnie na to samo co opencaching.pl

**Comment by deg-pl** [comment]
I think better will be:
`Redirect permanent / http://opencaching.pl/`
@wrygiel @andrixnet what are you thinking about it?

**Comment by wrygiel** [comment]
Permanent - ok.

**Comment by wrygiel** [comment]
I'm reverting this, as the means to debug #513.

**Comment by wrygiel** [comment]
It seems we need to support the www prefix, at least for OKAPI requests.

**Pull request merged**
