### PR TITLE
Display of final waypoint description to OpenChecker result

### PR DESCRIPTION
**Pull request by andrixnet**
Added display of final waypoint description to OpenChecker result when user has entered correct coordinates.

Improved several translations.

Added configuration to enable or disable showing final description.

Add $config['oc']['options']['show_final'] = 1; to your settings.inc.php to enable this feature.

### CODE REVIEW

**Comment by andrixnet** [comment]
A few bits I wrote are IMO horrible. They work well. But I am sure there is a better way. Also config rework will help improve.

**Comment by andrixnet** [comment]
@harrieklomp @wloczynutka please check the changes in strings.

**Comment by harrieklomp** [comment]
Very nice made :+1:  , but i see some strange things. When use plain text via "make waypoint" there is no "enter". To start a new line user need to use a < / b r >. This plain text is placed nice in the box.

Another issue is when use HTML via our editor. I make a coloured text in our editor and copy the code in the waypoint description. This is not placed in the textbox itself but under the textbox.
Please see screenshots below.
selectie_011
selectie_010

There are some options.

- Notify user with a line to use < / b r > to start a new line. Or show a link to these tags.
- Filter out  HTML code copied from editor.
- Place HTML code in the box.

**Comment by andrixnet** [comment]
Correct newline tag is `<br />`

**Comment by andrixnet** [comment]
I made the box to highlight the waypoint description itself.
I would suggest: 
- filter out HTML (should not be present in the description anyway)
- replace newlines with `<br />` dynamically, so that newlines are visually preserved

**Comment by harrieklomp** [comment]
I agree with andrixnet

**Comment by mzylowski** [comment]
As I understand, there is Work In Progress status?

**Comment by andrixnet** [comment]
I was able to make the changes required to show the info, but I need some help to finalize the two points in https://github.com/opencaching/opencaching-pl/pull/590#issuecomment-216021654

**Comment by andrixnet** [comment]
Will try to continue and solve this after https://github.com/opencaching/opencaching-pl/pull/654

**Comment by andrixnet** [comment]
Porting these changes to https://github.com/opencaching/opencaching-pl/pull/654

**Pull request closed without merging**
