### PR TITLE
Update en.php

### PR DESCRIPTION
**Pull request by Opencachingna**
Various improvements by a native English speaker and opencaching.us admin

### CODE REVIEW

**Comment by Opencachingna** [comment]
Oh crap, I forgot something, and it's a big one. That "We are using cookies which help us to improve our service." pop up on the bottom of the page when you first log in? That is not good English to a native speaker. I was going to look at some examples of what text some other sites use, and I forgot to go back to that.

**Comment by harrieklomp** [comment]
Can happen :-) .
You can edit this file online. When corrections are made than those stars can also be removed from different lines.

**Comment by Opencachingna** [comment]
@harrieklomp I can click on the file "attached" to my original post. Are you saying I should open that link up, and edit from there?

**Comment by andrixnet** [comment]
Will rework these together with changes by OCUK Team.

**Comment by andrixnet** [comment]
Closing. Superseeded by https://github.com/andrixnet/opencaching-pl/commit/91aa446030291f7a9842c2a157d77995460d3e41

**Pull request closed without merging**
