### PR TITLE
Next few changes - see commit messages

### PR DESCRIPTION
**Pull request by kojoty**

### CODE REVIEW

**Comment by kojoty** [comment]
@deg-pl, @harrieklomp, @andrixnet 

Please check if in your nodes settings.inc.php all calls to class **"cache"** (/lib/cache.php) are removed:

all things like: **cache::TYPE_TRADITIONAL** should be replaced to **GeoCacheCommons::TYPE_TRADITIONAL**

After merge this PR there will not be /lib/cache.php anymore.

**Comment by deg-pl** [comment]
@kojoty It produces error "ErrorException: ClassPathDictionary::getClassPath: ERROR: Trying to load unknown class: GeoCacheCommons" (in settings.inc.php)

**Comment by kojoty** [comment]
> @kojoty It produces error "ErrorException: ClassPathDictionary::getClassPath: ERROR: Trying to load unknown class: GeoCacheCommons" (in settings.inc.php)

Just add:
`use GeoCacheCommons` to settings.inc.php - it should works then without any issue. That's why I wrote comment above.

**Comment by harrieklomp** [comment]
Done at OCNL

**Comment by harrieklomp** [comment]
Done on OCUS

**Comment by deg-pl** [comment]
Done on OC PL and OC UK.

@kojoty Tak to jest, jeśli się zmienia konfigurację OC o północy między układaniem paneli a układaniem paneli ;). Dzięki.

**Comment by kojoty** [comment]
> Done on OC PL and OC UK.
> 
> @kojoty Tak to jest, jeśli się zmienia konfigurację OC o północy między układaniem paneli a układaniem paneli ;). Dzięki.

bo jest stara zasada przodków którą znano już prawdopodobnie w XVIw.: niedziela dzień święty - w niedzielę nie trzeba paneli układać - trzeba wtedy kod OC refaktorować!

**Comment by andrixnet** [comment]
OCRO and OCUS pending. 
Does this PR influence this:  https://github.com/opencaching/opencaching-pl/pull/2087 ?

**Comment by kojoty** [comment]
> OCRO and OCUS pending.
> Does this PR influence this: #2087 ?

I afraid the answer must be: YES
andrixnet: #2087 is huge, and it seems to be much more important - what is a way to merge it? 
Is this ready in your opinion? If yes, I can sit and review it today evening (250+ files - it will be cool I guess) - my smaller PR can wait...

**Comment by andrixnet** [comment]
IMO it is ready, at least according to my experience and knowledge of the code and all the research I did. There still is however a chance I might have missed something. 

See it live here: http://ocro.dev.andrix.eu/

**Comment by andrixnet** [comment]
I will try to be around the computer in the evening, 22:00 - 24:00 EET

**Comment by kojoty** [comment]
OK, I've checked and can confirm that the conficts with BIG PR #2087 (with new types) are quite easy to resolve - if OCUS and OCRO are ready (no **_cache::_**  use in settings.inc.php) we can merge this.

**Comment by kojoty** [comment]
@andrixnet Can you confirm that OCRo and OCUs are read for this commit - I mean no references to cache:: in settings.inc.php

I would like to merge this - and next I will resolve conflicts in #2087 when we decide to merge it.

**Comment by andrixnet** [comment]
OCRO has 
```
    $config['forbidenCacheTypes'] = array(
        cache::TYPE_GEOPATHFINAL
    );
```
I droppped it.
(anyway, with https://github.com/opencaching/opencaching-pl/pull/2087 it becomes invalid anyway).

Beware that `settingsDefault.inc.php` still contains references:
```
    /**
     * not allowed cache types (user cannot create caches of this types).
     *
     * Cachetypes must be lib/cache.php constant TYPE_*
     */
    'forbidenCacheTypes' => array(
        cache::TYPE_VIRTUAL,
        cache::TYPE_WEBCAM,
        cache::TYPE_GEOPATHFINAL
    ),
    /**
     * cache limits for user. If user is allowed to place limited nomber of spec
     * place cachetype and limit here.
     *
     * Cachetypes must be lib/cache.php constant TYPE_*
     */
    'cacheLimitByTypePerUser' => array(
        cache::TYPE_OWNCACHE => 1,
    ),
```

**Comment by kojoty** [comment]
@andrixnet Thanks, 

don't worry about settingsDefault.inc.php - this is a part of the code so I can control it by repo modification - opposite to settings.inc.php where I don't have an access

**Pull request merged**
