### PR TITLE
Map fixes

### PR DESCRIPTION
**Pull request by following5**
This fixes issues #1778 and #1781.

### CODE REVIEW

**Comment by following5** [comment]
Have also added a fix for #1779 here.

**Comment by deg-pl** [comment]
@kojoty Dasz radę w to zerknąć? Mapy to zdecydowanie Twój kawałek kodu ;)

**Comment by kojoty** [comment]
@deg-pl I'll try to take a look at this evening.

**Comment by following5** [comment]
> The map view for search results and geopaths does not work properly on my develsite 

var/searchdata directory was missing. Now all tested. ;)

**Comment by deg-pl** [comment]
@following5 PR merged, but ignored caches are still visible on the map.

**Comment by following5** [comment]
Now it works. There was an Okapi bug.

**Pull request merged**
