### PR TITLE
Openchecker translation and fixes

### PR DESCRIPTION
**Pull request by andrixnet**
Solved https://github.com/opencaching/opencaching-pl/issues/649

### CODE REVIEW

**Comment by andrixnet** [comment]
Changes can be viewed on OCRO live for the next few days.

**Comment by andrixnet** [comment]
Not sure how, but changes to docs/system/ocpl-update.extended.sh equivalent to https://github.com/opencaching/opencaching-pl/pull/589 got into this. Sorry.

**Comment by andrixnet** [comment]
- defined OpenChecker as a module. (resources in /modules/openchecker)
- added specific settings (attempts, time, pagination are configurable)
- can be enabled or disabled sitewide
- renamed all files and links
- translated all code variables and functions to english
- renamed and reorganized strings
- corrected a few display inconsistencies
- corrected invalid HTML
- added proper labels for radio/checkboxes in newwp/editwp
- corrected count bug (was: sql query counted all caches, displayed only
  active)
- reorganized caches table a bit
- style improvements
- improved "BACK" links on help page

TODO:
- integrate #590
- store checks in database rather then session (logging out resets your attempts count)
- rename database tables and fields according
- apply cache types object
- apply cache status properly
- remove / rewrite LIMIT 0,1000 ?

**Comment by andrixnet** [comment]
Please rename **Component_Opensprawdzacz** to **Component_OpenChecker** in GitHub Labels.

**Comment by andrixnet** [comment]
Done and tested. 
Changes can be seen live on OCRO. 

Ready to be merged.

**Comment by mzylowski** [comment]
@kojoty 
Please rename Component_Opensprawdzacz to Component_OpenChecker in GitHub Labels. ;]

**Comment by deg-pl** [comment]
@mzylowski I've changed ;)

**Comment by mzylowski** [comment]
Ohh... I also could do that. Sorry.

**Pull request merged**
