### PR TITLE
remove default country PL

### PR DESCRIPTION
**Pull request by following5**
Don't think there is something like a "default country". The setting for OC PL already is in site.pl.php.

### CODE REVIEW

**Comment by kojoty** [comment]
@following5 
This is detailed case but I write it:
my general idea of default config is to ensure that site with only "defaults" is able to work - then node admin can configure/customize what is needed 

I'm not sure if set by default not accepted value and make user to change it by exception is not (in my opinion) the best solution - what're your thoughts?

**Comment by kojoty** [comment]
right now we have a mess in config - most of config vars are still in old settings.* files - a few new settings is refactored to new files

I think we need to continue refactor and one day we also clean up the config files. 
I believe noone needs to set up oc node without customization but maybe at the beginning let's not make the new admin to configure more than necessary.

Maybe it should be better to set EN instead of PL - PL was only because I thought also about dev sites - right now most OCPL code devs are from PL - but this is nothing important

**Comment by following5** [comment]
There is no country "EN". :-)

Agree that the default language may be set to 'en'.

**Comment by following5** [comment]
We could allow to set this in settings.inc.php, if it is not configured in Config/site.XX.php. Then

* it is still easy to set up a site (no code change needed),
* the site can be set up so that it fully works,
* the authoritative settings stays in Config/site - it cannot be overridden locally.

**Comment by following5** [comment]
What about using the TLD of the site's URL as country default?

**Comment by following5** [comment]
will make a new proposal

**Pull request closed without merging**
