### PR TITLE
A few small site improvements

### PR DESCRIPTION
**Pull request by deg-pl**

### CODE REVIEW

**Comment by deg-pl** [comment]
@andrixnet @harrieklomp 
Generation of data for charts on Statistics page now is done via cron, NOT every time user view statistics page. This was very time consuming (about 3 secs per 1 pageview). Now it should be done via cron - once a day (or even less frequently!)
**Please add something like this to your crontab**:
`1    0   *   *   *   wget -O - -q http://opencaching.pl/tpl/stdstyle/etc/write_chartsdata.php`
(of course - change domain to yours ;) )

**Comment by harrieklomp** [comment]
Done on ONCL

**Comment by andrixnet** [comment]
cron job implemented on OCRO.

@deg-pl : could you (or another developer from the polish team) place/update under `/docs` a complete set of current cronjobs?

**Comment by deg-pl** [comment]
@andrixnet see to commit da7466e61e4ee6443448ff7281c757b8b72b7c98 - I've updated docs.

**Comment by andrixnet** [comment]
Thank you very much. 
It would be great to keep this file updated each time there are cronjobs changes.

**Pull request merged**
