### PR TITLE
Option for hidding powerTrails on map. Fixes #155

### LINKED ISSUE #155: filtrowanie geoŚcieżek zdobytych i/lub posiadanych
```
(You can use Polish or English, whichever you think is better.)
Witam:)
Jaka są możliwości techniczne aby nie wyświetlały się ikonki na mapie 
geościeżek te, które są już przez użytkownika zdobyte lub których jest 
założycielem? Można by zrobić opcje wyboru tak jak na ogólnej mapie 
skrzynek.
pozdrawiam
atena.pl
```

Original issue reported on code.google.com by `atenakat...@gmail.com` on 6 Aug 2014 at 6:38

### PR DESCRIPTION
**Pull request by mzylowski**
@harrieklomp @andrixnet Maybe you want look and change translations ;]
@deg-pl You probably also are interested of this :)
selection_025

### CODE REVIEW

**Comment by harrieklomp** [comment]
I will correct the Dutch translations when this is committed :-)

**Comment by deg-pl** [comment]
WOW! WOW! WOW! You're the best speed demon I know!
(skąd ja Ci qrna teraz te dziewice znajdę...)

**Comment by kojoty** [comment]
No jak nie masz dziewic to albo musisz cos upolować albo nie wiem... sam
idź do czarodzieja i... jakoś się dogadaj...

**Comment by andrixnet** [comment]
I will handle translation later, when I get to the romanian file. 
Meanwhile feel free to just place the english strings. Thank you.

**Pull request merged**
